package zxn.ws.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-04-28T10:41:16.784+08:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "Regedit", 
                  wsdlLocation = "http://localhost:3307/CXFWS/services/Regedit?wsdl",
                  targetNamespace = "http://service.ws.zxn/") 
public class Regedit_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.zxn/", "Regedit");
    public final static QName RegeditServiceImplPort = new QName("http://service.ws.zxn/", "RegeditServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:3307/CXFWS/services/Regedit?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Regedit_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:3307/CXFWS/services/Regedit?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Regedit_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Regedit_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Regedit_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Regedit_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Regedit_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Regedit_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RegeditService
     */
    @WebEndpoint(name = "RegeditServiceImplPort")
    public RegeditService getRegeditServiceImplPort() {
        return super.getPort(RegeditServiceImplPort, RegeditService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegeditService
     */
    @WebEndpoint(name = "RegeditServiceImplPort")
    public RegeditService getRegeditServiceImplPort(WebServiceFeature... features) {
        return super.getPort(RegeditServiceImplPort, RegeditService.class, features);
    }

}
